### ISSUE TITLE
Crash Bug: ExecuteStaticAsync

### ISSUE THREAD

**Issue by blakepell** [blakepell/AvalonMudClient#49]
From the interactive Lua panel:

```
Unhandled exception (TaskScheduler.UnobservedTaskException)
Unhandled exception in Avalon v2022.7.3.2
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (One or more errors occurred. (')' expected (to close '(' at line 5) near '<eof>'))

One or more errors occurred. (')' expected (to close '(' at line 5) near '<eof>')
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MoonSharp.Interpreter.Script.<>c__DisplayClass56_0.<DoStringAsync>b__0(Task`1 prevTask)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Avalon.Common.Scripting.MoonSharpEngine.ExecuteStaticAsync[T](String code)

```

**Comment by blakepell** [comment]
This is fixed and will be included in the next release.
